twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_5_layout.html.twig']

    globals:
        artPicture_folder: '/uploads/artPicture/'

when@test:
    twig:
        strict_variables: true
